### ISSUE TITLE
Missing Things NEED TO BE ADDED

### ISSUE THREAD

**Issue by AmongUsafk** [Among-Us-Modding/Laboratory#3]
hi i love this repo coz there some features that GameToons Gaming Channel use it but there some missing features recently :

-  **Custom Player Body** :  it would be cool if this added to Laboratory with every frame moving + Shadow
- **Custom Maps** for example changing the fungle map color custom map prefab maybe and etc... 
- **Improuve Lava Color** when u change the lava color in polus it's not like the original with bulles (i don't talk about color)

Reply me if any of thoses will gonna added in the feature !

**Comment by simonkellly** [comment]
Hello, I am not taking feature requests at the moment
